#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','I','.',' ','-',
        'I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ',
        '-','f','P','I','C',' ','-','f','n','o','-','c','o','m','m','o','n',' ',
        '-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D','O','P',
        'E','N','S','S','L','_','T','H','R','E','A','D','S',' ','-','D','_','R',
        'E','E','N','T','R','A','N','T',' ','-','D','D','S','O','_','D','L','F',
        'C','N',' ','-','D','H','A','V','E','_','D','L','F','C','N','_','H',' ',
        '-','a','r','c','h',' ','x','8','6','_','6','4',' ','-','O','3',' ','-',
        'D','L','_','E','N','D','I','A','N',' ','-','D','M','D','3','2','_','R',
        'E','G','_','T','=','i','n','t',' ','-','W','a','l','l',' ','-','D','O',
        'P','E','N','S','S','L','_','I','A','3','2','_','S','S','E','2',' ','-',
        'D','O','P','E','N','S','S','L','_','B','N','_','A','S','M','_','M','O',
        'N','T',' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S','H',
        'A','2','5','6','_','A','S','M',' ','-','D','S','H','A','5','1','2','_',
        'A','S','M',' ','-','D','M','D','5','_','A','S','M',' ','-','D','A','E',
        'S','_','A','S','M',' ','-','D','W','H','I','R','L','P','O','O','L','_',
        'A','S','M','\0'
    };
    #define PLATFORM "platform: darwin64-x86_64-cc"
    #define DATE "built on: Tue Apr  7 14:33:05 2020"
#endif
